baseurl = "http://www.encabulator.io/"
title = "Encabulator"
theme = "vec"
languageCode = "en-us"
paginate = 10
googleAnalytics = "UA-89590086-1"


[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "posts"
    weight = 0
    url = "/posts"
  [[menu.main]]
    name = "wopr"
    weight = 1
    url = "/wopr"
  [[menu.main]]
    name = "contact"
    weight = 2
    url = "/contact"
  [[menu.main]]
    name = "faq"
    weight = 3
    url = "/faq"

[params]
  Keywords = "encabulator, encabulation, retro, technology, maker, tinker"
  Description = "Encabulation"
  Avater = "img/turboencabulator-primary.idge.jpg"
  SelfIntro = "Coming soon..."
  Email = "coming@soon.com"
