version: 2
jobs:
  build:
    docker: 
      - image: kotancode/hugobuilder:latest
    
    working_directory: /tmp/work
  
    steps:
      - checkout
    
      - run: 
          name: Generate via hugo
          command: |
            hugo -v
        
      - setup_remote_docker

      - run:
          name: Build and push Docker image
          command: |
            TAG="0.1.${CIRCLE_BUILD_NUM}"
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker build -t encabulatorio/encabulator-site:$TAG .
              docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              docker push encabulatorio/encabulator-site:$TAG      
            fi
