version: 2
jobs:
  build:
    docker: 
      - image: jojomi/hugo:latest
    
    working_directory: ~/
  
    steps:
      - checkout

      - run: 
          name: Generate via hugo
          command: |
            hugo -v
        
      - setup_remote_docker

      - run:
          name: Build and push Docker image
          command: |
            TAG="0.1.${CIRCLE_BUILD_NUM}"
            docker build -t circleci/cci-demo-docker:$TAG .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push circleci/cci-demo-docker:$TAG      